# Generated by Django 5.2.2 on 2025-06-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamosapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='tipo',
            field=models.CharField(choices=[('TRADICIONAL', 'Tradicional (Cuotas fijas)'), ('DINAMICO', 'Dinámico (Abono a capital)')], default='TRADICIONAL', max_length=20),
        ),
    ]
