# Generated by Django 5.2.2 on 2025-06-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamosapp', '0002_prestamo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='pago_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cuota',
            unique_together={('prestamo', 'numero_cuota')},
        ),
    ]
